
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    threads:
      max: 200
      min-spare: 4
  shutdown: graceful


# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    serialization:
      write_bigdecimal_as_plain: true

  web:
    resources:
      chain:
        compressed: true
        cache: true
      cache:
        period: 2592000
  mvc:
    static-path-pattern: /static/**
#      add-mappings: false



# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: 1quashedfsdf@3dffDfs

    expireTime: 720
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.bistro.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /swagger

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

feign:
  httpclient:
    enabled: false
    time-to-live: 180
    connection-timeout: 3000
  okhttp:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 30000
      seamlessClient:
        connect-timeout: 3000
        read-timeout: 10000



websocket:
  enable: true

